apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: test-chatbot-seret-12
  janus-idp.io/tekton: test-chatbot-seret-12
  backstage.io/kubernetes-id: test-chatbot-seret-12
  backstage.io/kubernetes-namespace: ai-rhdh-app-development 
  app.kubernetes.io/part-of: test-chatbot-seret-12
resources: 
- initialize-namespace.yaml
- deployment.yaml
- route.yaml
- service.yaml
- model-config.yaml
- rhoai/
