kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: test-chatbot-seret-12-dsp-job-rolebinding
subjects:
  - kind: ServiceAccount
    name: test-chatbot-seret-12-dsp-job
    namespace: ai-rhdh-app-development
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: test-chatbot-seret-12-dsp-job-role